/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (G-Police: Weapons of Justice)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80035020u
#define func_80035020 BootEntry  /* alias */
